### ISSUE TITLE
Problème d'installation

### ISSUE THREAD

**Issue by Griset** [fontanf/columngenerationsolver#1]
Bonjour Florian, 

Je suis à la R&D d'EDF, vous etiez venu faire une formation chez nous je crois il y a 1 ans. Je souhaiterais installer votre librairie afin de réaliser une comparaison entre celle-ci et d'autres librairie de génération de colonnes. J'ai un soucis concernant la compilation avec bazel, j'ai installé bazel sur ma machine mais je ne sais pas où je suis sensé me placer pour lancer la commande:

bazel build --define cplex=true 

j'obtiens la sortie suivante : 
WARNING: Output base '/home/d07876/.cache/bazel/_bazel_d07876/1ce43636e10804d26a559fbfdfd36fb2' is on NFS. This may lead to surprising failures and undetermined behavior.
WARNING: Usage: bazel build <options> <targets>.
Invoke `bazel help build` for full description of usage and options.
Your request is correct, but requested an empty set of targets. Nothing will be built.
INFO: Analyzed 0 targets (0 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 0.158s, Critical Path: 0.01s
INFO: 1 process: 1 internal.

Pourriez-vous me donner des indications supplémentaires ? merci d'avance

**Comment by fontanf** [comment]
Bonjour,

Il manque `-- //...` à la fin de la commande de compilation :
```
bazel build --define cplex=true -- //...
```

**Comment by Griset** [comment]
C'est bon merci
